spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/jpashop;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false

# H2 Console 설정
spring.h2.console.enabled: true
spring.h2.console.path: /database-console

# Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
