import io.github.cdimascio.dotenv.Dotenv;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
    
@Configuration
public class DotenvConfig {
  @Bean
  public Dotenv dotenv() {
  return Dotenv.configure().ignoreIfMissing().load();
  }
}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: ${@dotenv.get("DB_PASSWORD")}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000